### ISSUE TITLE
linux PC or linux server?

### ISSUE THREAD

**Issue by zulihit** [UMass-Foundation-Model/Co-LLM-Agents#28]
Hello, I would like to inquire if your program is running on a local Linux computer or a remote Linux server. If I use a remote Linux server, may I not be able to see the visual interface. I am not sure how to set up and run your program

**Comment by Icefoxzhx** [comment]
Hi, as we mentioned in the [Setup](https://github.com/UMass-Foundation-Model/Co-LLM-Agents/tree/master/tdw_mat#setup), configuring TDW on remote servers may be intricate, for more detailed guidelines please refer to the [TDW repo](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/setup/install.md).
Most of our experiments are conducted on a local Linux server with displays. We also tested the code on a remote Linux server. For running on remote server, there will be no displays, since the server is headless.
